spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
  liquibase:
    enabled: false
  devtools:
    add-properties: false
  profiles:
    active: @profilesActive@
server:
  port: 8000
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: service.api.mybatis.entity
