

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/app?serverTimezone=UTC
    username: root
    password: root
  liquibase:
    enabled: false
  devtools:
    add-properties: true
server:
  port: 8001
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: service.api.mybatis.entity


