spring:
  liquibase:
    enabled: false
  devtools:
    add-properties: false
  profiles:
    include: conf
server:
  port: 8002
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: service.api.mybatis.entity
