spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  liquibase:
    enabled: false
  devtools:
    add-properties: true
server:
  port: 8003