logging:
  config: classpath:log4j2.yml
spring:
  profiles:
    include: i18n,redis,datasource,jpa,jwt,swagger,flyway,security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 8088
  servlet:
    context-path: /api